"use client";

import { useEffect, useState } from "react";
import { Heart, Loader2, Star } from "lucide-react";
import { toast } from "sonner";

type Review = { id: number; rating: number; comment?: string | null; authorName: string; createdAt: string };

export function WishlistToggle({ courseId, initialSaved = false }: { courseId: number; initialSaved?: boolean }) {
  const [saved, setSaved] = useState(initialSaved);
  const [loading, setLoading] = useState(false);
  async function toggle() { setLoading(true); try { const response = await fetch(saved ? `/api/wishlist?courseId=${courseId}` : "/api/wishlist", { method: saved ? "DELETE" : "POST", headers: saved ? undefined : { "Content-Type": "application/json" }, body: saved ? undefined : JSON.stringify({ courseId }) }); if (!response.ok) throw new Error("Entre para salvar cursos na Lista de Desejos."); setSaved(!saved); window.dispatchEvent(new CustomEvent("wishlist:changed", { detail: { saved: !saved, courseId } })); toast.success(saved ? "Curso removido dos desejos." : "Curso salvo nos desejos."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível atualizar os desejos."); } finally { setLoading(false); } }
  return <button type="button" onClick={toggle} disabled={loading} aria-label={saved ? "Remover dos desejos" : "Salvar nos desejos"} className={`inline-flex items-center justify-center gap-2 rounded-xl border px-3 py-2 text-xs font-black transition ${saved ? "border-red-600 bg-red-50 text-red-600" : "border-white/40 bg-white/10 text-white hover:bg-white/20"}`}>{loading ? <Loader2 className="animate-spin" size={15} /> : <Heart size={15} className={saved ? "fill-red-600" : ""} />} {saved ? "Salvo" : "Desejos"}</button>;
}

export function CourseEngagement({ courseId }: { courseId: number }) {
  const [reviews, setReviews] = useState<Review[]>([]);
  const [average, setAverage] = useState(0);
  const [count, setCount] = useState(0);
  const [saved, setSaved] = useState(false);
  const [rating, setRating] = useState(5);
  const [comment, setComment] = useState("");
  const [saving, setSaving] = useState(false);
  const [wishlistLoading, setWishlistLoading] = useState(false);
  useEffect(() => { fetch(`/api/course-reviews/${courseId}`).then((r) => r.json()).then((data) => { setReviews(data.reviews || []); setAverage(data.average || 0); setCount(data.count || 0); }).catch(() => undefined); fetch("/api/wishlist").then((r) => r.ok ? r.json() : null).then((data) => setSaved(Boolean(data?.items?.some((item: { course?: { id?: number } | null }) => item.course?.id === courseId)))).catch(() => undefined); }, [courseId]);
  async function toggleWishlist() { setWishlistLoading(true); try { const response = await fetch(saved ? `/api/wishlist?courseId=${courseId}` : "/api/wishlist", { method: saved ? "DELETE" : "POST", headers: saved ? undefined : { "Content-Type": "application/json" }, body: saved ? undefined : JSON.stringify({ courseId }) }); if (!response.ok) throw new Error("Entre para salvar cursos na Lista de Desejos."); setSaved(!saved); window.dispatchEvent(new CustomEvent("wishlist:changed", { detail: { saved: !saved, courseId } })); toast.success(saved ? "Curso removido da Lista de Desejos." : "Curso salvo na Lista de Desejos."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível atualizar a lista."); } finally { setWishlistLoading(false); } }
  async function submitReview(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { const response = await fetch(`/api/course-reviews/${courseId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, comment }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível publicar a avaliação."); toast.success("Avaliação salva."); const refresh = await fetch(`/api/course-reviews/${courseId}`).then((r) => r.json()); setReviews(refresh.reviews || []); setAverage(refresh.average || 0); setCount(refresh.count || 0); setComment(""); } catch (error) { toast.error(error instanceof Error ? error.message : "Erro ao avaliar curso."); } finally { setSaving(false); } }
  return <section className="space-y-6 border-t border-gray-200 pt-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black text-gray-900">Avaliações dos alunos</h2><p className="mt-1 text-sm text-gray-600">{count ? `${average.toFixed(1)} de 5 • ${count} avaliação(ões)` : "Ainda não há avaliações publicadas."}</p></div><button onClick={toggleWishlist} disabled={wishlistLoading} className={`inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold ${saved ? "border-red-600 bg-red-50 text-red-600" : "border-gray-300 text-gray-700 hover:border-red-500 hover:text-red-600"}`}>{wishlistLoading ? <Loader2 className="animate-spin" size={16} /> : <Heart size={16} className={saved ? "fill-red-600" : ""} />} {saved ? "Salvo nos desejos" : "Salvar curso"}</button></div><div className="grid gap-4 md:grid-cols-2">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-gray-900">{review.authorName}</strong><span className="flex items-center gap-1 text-amber-500">{Array.from({ length: review.rating }).map((_, index) => <Star key={index} size={14} className="fill-amber-500" />)}</span></div>{review.comment && <p className="mt-3 text-sm leading-6 text-gray-600">{review.comment}</p>}</article>)}</div><form onSubmit={submitReview} className="rounded-2xl border border-gray-200 bg-gray-50 p-5"><h3 className="font-bold text-gray-900">Concluiu este curso? Avalie sua experiência</h3><div className="mt-3 flex items-center gap-1">{[1, 2, 3, 4, 5].map((value) => <button type="button" key={value} onClick={() => setRating(value)} aria-label={`${value} estrelas`}><Star size={24} className={value <= rating ? "fill-amber-400 text-amber-400" : "text-gray-300"} /></button>)}</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={2000} placeholder="Compartilhe um comentário (opcional)" className="mt-3 min-h-24 w-full rounded-xl border border-gray-300 bg-white p-3 text-sm" /><button disabled={saving} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-60">{saving && <Loader2 className="animate-spin" size={16} />} Publicar avaliação</button></form></section>;
}
