"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Building2, Plus, RefreshCw, Users } from "lucide-react";

type ExternalClass = { id: number; className: string; institution: string; courseName: string; academicTerm: string; students?: Array<unknown> };

export function ExternalClassesManager() {
  const [classes, setClasses] = useState<ExternalClass[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/professor/external-classes", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Não foi possível carregar as turmas."); setClasses(payload.classes || payload.data || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar as turmas."); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  return <section className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-red-600">Gestão</p><h2 className="mt-1 text-2xl font-black tracking-tight">Turmas cadastradas</h2><p className="mt-1 text-sm text-muted-foreground">Consulte e abra cada turma sem misturar criação, matrícula e acompanhamento.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold hover:bg-muted"><RefreshCw size={15} /> Atualizar</button><Link href="/professor/turmas-externas/criar" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-red-600 px-3 text-sm font-bold text-white hover:bg-red-700"><Plus size={15} /> Nova turma</Link></div></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}{loading ? <div className="rounded-2xl border border-border bg-card p-8 text-sm text-muted-foreground">Carregando turmas...</div> : classes.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center"><Building2 className="mx-auto text-muted-foreground" /><h3 className="mt-3 font-black">Nenhuma turma cadastrada</h3><p className="mt-1 text-sm text-muted-foreground">Comece criando a primeira turma externa.</p></div> : <div className="grid gap-3 md:grid-cols-2">{classes.map((item) => <article key={item.id} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{item.institution}</p><h3 className="mt-1 text-lg font-black">{item.className}</h3><p className="mt-1 text-sm text-muted-foreground">{item.courseName} · {item.academicTerm}</p></div><Users size={19} className="text-red-600" /></div><div className="mt-4 flex items-center justify-between border-t border-border pt-3 text-sm"><span className="text-muted-foreground">{item.students?.length || 0} aluno(s)</span><Link href={`/professor/turmas-externas/${item.id}`} className="inline-flex items-center gap-1 font-bold text-red-600 hover:text-red-700">Abrir turma <ArrowRight size={15} /></Link></div></article>)}</div>}</section>;
}
