"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function ExternalClassCreateForm() {
  const router = useRouter(); const [form, setForm] = useState({ institution: "IsF", className: "", courseName: "", academicTerm: "", description: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/professor/external-classes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "createClass", ...form }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Não foi possível criar a turma."); router.push("/professor/turmas-externas/gerenciar"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível criar a turma."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="max-w-2xl space-y-5 rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Instituição<select value={form.institution} onChange={(e) => update("institution", e.target.value)} className="mt-2 w-full rounded-xl border border-border bg-background p-3"><option>IsF</option><option>PROFICI</option><option>SIMAL</option><option>Megaworks</option><option>UFBA</option><option>Outra</option></select></label><label className="text-sm font-bold">Período letivo<input required value={form.academicTerm} onChange={(e) => update("academicTerm", e.target.value)} placeholder="2026.1" className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label></div><label className="block text-sm font-bold">Nome da turma<input required value={form.className} onChange={(e) => update("className", e.target.value)} placeholder="Turma Vespertina" className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="block text-sm font-bold">Curso ou disciplina<input required value={form.courseName} onChange={(e) => update("courseName", e.target.value)} placeholder="Inglês Instrumental" className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="block text-sm font-bold">Descrição<span className="mt-2 block text-xs font-normal text-muted-foreground">Opcional</span><textarea value={form.description} onChange={(e) => update("description", e.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={() => router.push("/professor/turmas-externas")} className="rounded-xl border border-border px-4 py-3 text-sm font-bold">Cancelar</button><button disabled={saving} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Salvando..." : "Criar turma"}</button></div></form>;
}
