"use client";

import { useEffect, useState } from "react";
import { Activity, CalendarDays, CheckCircle2, ClipboardCheck, GraduationCap, Users } from "lucide-react";

type Student = { id: number; name: string | null; email: string | null };
type Summary = { sessions: Array<{ id: number; title: string; scheduledAt: string | Date; status: string }>; activities: Array<{ id: number; title: string; dueDate: string | Date | null }>; attendances: Array<{ studentId: number; status: string }>; averageProgress: number; attendanceRate: number; completedActivities: number; totalActivities: number };
type Props = { offer: { id?: number; offerName: string; academicTerm: string; institution: string | null; status: string; modality: string | null; classDays: string | null; classTime: string | null }; course: { title: string; level: string } | null; students: Student[]; role: string };

const tabs = [
  { id: "overview", label: "Visão geral", icon: Activity }, { id: "students", label: "Alunos", icon: Users }, { id: "sessions", label: "Sessões", icon: CalendarDays },
  { id: "attendance", label: "Presença", icon: ClipboardCheck }, { id: "activities", label: "Atividades", icon: GraduationCap }, { id: "progress", label: "Progresso", icon: CheckCircle2 },
] as const;

export function InternalClassDetail({ offer, course, students, role }: Props) {
  const [activeTab, setActiveTab] = useState<(typeof tabs)[number]["id"]>("overview");
  const [summary, setSummary] = useState<Summary | null>(null);
  useEffect(() => { if (!offer.id) return; const timer = window.setTimeout(() => { void fetch(`/api/course-offers/${offer.id}/academic-summary`).then((response) => response.ok ? response.json() : null).then(setSummary).catch(() => setSummary(null)); }, 0); return () => window.clearTimeout(timer); }, [offer.id]);
  const statusLabel = offer.status === "published" ? "Publicada" : offer.status === "archived" ? "Arquivada" : "Rascunho";
  const metrics = [{ label: "Progresso médio", value: `${summary?.averageProgress ?? 0}%` }, { label: "Presença", value: `${summary?.attendanceRate ?? 0}%` }, { label: "Atividades concluídas", value: `${summary?.completedActivities ?? 0}/${summary?.totalActivities ?? 0}` }];
  return <div className="flex flex-col gap-5">
    <div className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-red-600">{course?.level ?? "Curso interno"} · {offer.academicTerm}</p><h1 className="mt-2 text-2xl font-black tracking-tight text-foreground sm:text-3xl">{offer.offerName}</h1><p className="mt-2 text-sm text-muted-foreground">{course?.title ?? "Curso não informado"}{offer.institution ? ` · ${offer.institution}` : ""}</p></div><span className="w-fit rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{statusLabel}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl bg-muted/50 p-4"><p className="text-xs font-semibold text-muted-foreground">{metric.label}</p><p className="mt-1 text-2xl font-black text-foreground">{metric.value}</p></div>)}</div></div>
    <div className="overflow-x-auto rounded-2xl border border-border bg-card p-2 shadow-sm"><div className="flex min-w-max gap-1" role="tablist" aria-label="Seções da turma">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" role="tab" aria-selected={activeTab === id} onClick={() => setActiveTab(id)} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-bold transition ${activeTab === id ? "bg-red-600 text-white" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon size={16} aria-hidden="true" />{label}</button>)}</div></div>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6" role="tabpanel"><h2 className="text-xl font-black text-foreground">{tabs.find((tab) => tab.id === activeTab)?.label}</h2>{activeTab === "students" ? <div className="mt-5 divide-y divide-border">{students.length ? students.map((student) => <div key={student.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-bold text-foreground">{student.name || "Aluno sem nome"}</p><p className="text-sm text-muted-foreground">{student.email || "E-mail não informado"}</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold text-muted-foreground">Ativo</span></div>) : <p className="py-8 text-sm text-muted-foreground">Nenhum aluno vinculado ainda.</p>}</div> : activeTab === "sessions" ? <div className="mt-5 flex flex-col gap-3">{summary?.sessions.length ? summary.sessions.map((session) => <div key={session.id} className="flex flex-col gap-1 rounded-xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><span className="font-bold text-foreground">{session.title}</span><span className="text-sm text-muted-foreground">{new Date(session.scheduledAt).toLocaleDateString("pt-BR")} · {session.status}</span></div>) : <p className="py-8 text-sm text-muted-foreground">Nenhuma sessão registrada.</p>}</div> : <><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{activeTab === "overview" ? "Acompanhe a operação da turma com dados acadêmicos reais." : "Os registros desta seção são carregados a partir dos vínculos acadêmicos existentes."}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl border border-dashed border-border p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{metric.label}</p><p className="mt-2 text-2xl font-black text-foreground">{metric.value}</p></div>)}</div><p className="mt-5 text-xs font-semibold text-muted-foreground">Acesso: {role === "admin" ? "administrador" : "professor responsável"}.</p></>}</section>
  </div>;
}
