"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, FileText, Loader2, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";

type Note = { id: number; lessonId: number; note: string; updatedAt: string; lesson?: { title?: string | null } | null };

export default function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [savingId, setSavingId] = useState<number | null>(null);
  useEffect(() => { fetch("/api/notes").then(async (r) => { if (!r.ok) throw new Error("Não foi possível carregar as anotações."); return r.json(); }).then((data) => setNotes(data.notes || [])).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => notes.filter((note) => `${note.lesson?.title || ""} ${note.note}`.toLowerCase().includes(query.toLowerCase())), [notes, query]);
  async function save(note: Note) { setSavingId(note.id); try { const r = await fetch("/api/notes", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonId: note.lessonId, note: note.note }) }); if (!r.ok) throw new Error("Não foi possível salvar."); toast.success("Anotação salva."); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro ao salvar."); } finally { setSavingId(null); } }
  async function remove(note: Note) { if (!window.confirm("Excluir esta anotação?")) return; const r = await fetch(`/api/notes?lessonId=${note.lessonId}`, { method: "DELETE" }); if (!r.ok) { toast.error("Não foi possível excluir."); return; } setNotes((current) => current.filter((item) => item.id !== note.id)); toast.success("Anotação excluída."); }
  function exportNotes() { const content = filtered.map((note) => `Aula: ${note.lesson?.title || `#${note.lessonId}`}\nAtualizada em: ${new Date(note.updatedAt).toLocaleString("pt-BR")}\n\n${note.note}\n\n---\n`).join("\n"); const blob = new Blob([content || "Nenhuma anotação encontrada."], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "minhas-anotacoes.txt"; anchor.click(); URL.revokeObjectURL(url); }

  return <div className="mx-auto max-w-5xl space-y-6 pb-12"><div className="flex flex-col justify-between gap-4 border-b border-gray-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-red-600">Estudo pessoal</p><h1 className="mt-2 text-3xl font-black text-gray-900">Central de Anotações</h1><p className="mt-2 text-gray-600">Pesquise e organize observações feitas nas aulas.</p></div><div className="flex flex-wrap gap-2"><button onClick={exportNotes} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-gray-300 px-4 text-sm font-bold text-gray-700 hover:border-red-500 hover:text-red-600"><Download size={16} /> Exportar texto</button><a href="/api/notes/export" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700"><Download size={16} /> Exportar PDF</a></div></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Pesquisar por aula ou conteúdo..." className="w-full rounded-2xl border border-gray-300 bg-white px-10 py-3 outline-none focus:border-red-500" /></div>{loading ? <div className="flex justify-center rounded-2xl border bg-white p-12"><Loader2 className="animate-spin text-red-600" /></div> : filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-gray-300 bg-white p-12 text-center text-gray-500"><FileText className="mx-auto mb-3 text-gray-400" />Você ainda não possui anotações salvas.</div> : <div className="space-y-4">{filtered.map((note) => <article key={note.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-bold text-gray-900">{note.lesson?.title || `Aula #${note.lessonId}`}</h2><p className="text-xs text-gray-500">Atualizada em {new Date(note.updatedAt).toLocaleString("pt-BR")}</p></div><div className="flex gap-2"><button onClick={() => remove(note)} aria-label="Excluir anotação" className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={16} /></button></div></div><textarea value={note.note} onChange={(e) => setNotes((current) => current.map((item) => item.id === note.id ? { ...item, note: e.target.value } : item))} className="min-h-28 w-full rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm text-gray-800 outline-none focus:border-red-500" /><button onClick={() => save(note)} disabled={savingId === note.id} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white hover:bg-red-700 disabled:opacity-60">{savingId === note.id && <Loader2 className="animate-spin" size={14} />} Salvar alteração</button></article>)}</div>}</div>;
}
