// Gerado automaticamente a partir de drizzle/migrations/*.sql
// SQL embutido diretamente no codigo (em vez de lido do disco em runtime)
// para evitar problemas de empacotamento de arquivos na Vercel.
// Ordem: 0000_stormy_freak -> 0001_common_sabra -> 0002_moaning_johnny_storm -> 0003_skinny_vermin
export const MIGRATION_STATEMENTS: string[] = [
  "CREATE TYPE \"public\".\"activity_type\" AS ENUM('quiz', 'exercise', 'assignment', 'speaking');",
  "CREATE TYPE \"public\".\"enrollment_status\" AS ENUM('active', 'completed', 'paused');",
  "CREATE TYPE \"public\".\"progress_status\" AS ENUM('pending', 'in_progress', 'completed');",
  "CREATE TYPE \"public\".\"role\" AS ENUM('user', 'admin');",
  "CREATE TABLE \"activities\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"courseId\" serial NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"type\" \"activity_type\" NOT NULL,\n\t\"dueDate\" timestamp,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"articles\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"slug\" varchar(255) NOT NULL,\n\t\"content\" text,\n\t\"category\" varchar(100),\n\t\"readingTime\" serial NOT NULL,\n\t\"published\" timestamp,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL,\n\tCONSTRAINT \"articles_slug_unique\" UNIQUE(\"slug\")\n);",
  "CREATE TABLE \"certificates\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"userId\" serial NOT NULL,\n\t\"courseId\" serial NOT NULL,\n\t\"level\" varchar(10) NOT NULL,\n\t\"issuedAt\" timestamp DEFAULT now() NOT NULL,\n\t\"certificateUrl\" varchar(500)\n);",
  "CREATE TABLE \"courses\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"level\" varchar(10) NOT NULL,\n\t\"modules\" integer DEFAULT 0,\n\t\"instructor\" varchar(255) DEFAULT 'Anderson Palafoz',\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"enrollments\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"userId\" serial NOT NULL,\n\t\"courseId\" serial NOT NULL,\n\t\"progress\" serial DEFAULT 0 NOT NULL,\n\t\"currentModule\" serial DEFAULT 0 NOT NULL,\n\t\"status\" \"enrollment_status\" DEFAULT 'active' NOT NULL,\n\t\"enrolledAt\" timestamp DEFAULT now() NOT NULL,\n\t\"completedAt\" timestamp\n);",
  "CREATE TABLE \"materials\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"category\" varchar(100) NOT NULL,\n\t\"level\" varchar(10) NOT NULL,\n\t\"fileUrl\" varchar(500),\n\t\"downloads\" serial DEFAULT 0 NOT NULL,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"userActivityProgress\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"userId\" serial NOT NULL,\n\t\"activityId\" serial NOT NULL,\n\t\"status\" \"progress_status\" DEFAULT 'pending' NOT NULL,\n\t\"score\" serial NOT NULL,\n\t\"submittedAt\" timestamp,\n\t\"completedAt\" timestamp\n);",
  "CREATE TABLE \"users\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"openId\" varchar(64) NOT NULL,\n\t\"name\" text,\n\t\"email\" varchar(320),\n\t\"loginMethod\" varchar(64),\n\t\"role\" \"role\" DEFAULT 'user' NOT NULL,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL,\n\t\"lastSignedIn\" timestamp DEFAULT now() NOT NULL,\n\tCONSTRAINT \"users_openId_unique\" UNIQUE(\"openId\")\n);",
  "CREATE TABLE \"lessonProgress\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"userId\" serial NOT NULL,\n\t\"lessonId\" serial NOT NULL,\n\t\"completed\" integer DEFAULT 0,\n\t\"watchedDuration\" integer DEFAULT 0,\n\t\"completedAt\" timestamp,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"lessons\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"moduleId\" serial NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"videoUrl\" varchar(500),\n\t\"duration\" integer,\n\t\"order\" integer NOT NULL,\n\t\"content\" text,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"modules\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"courseId\" serial NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"order\" integer NOT NULL,\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"progress\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"userId\" integer NOT NULL,\n\t\"courseId\" integer NOT NULL,\n\t\"enrollmentId\" integer,\n\t\"lessonsCompleted\" integer DEFAULT 0,\n\t\"totalLessons\" integer DEFAULT 0,\n\t\"percentageCompleted\" integer DEFAULT 0,\n\t\"status\" \"progress_status\" DEFAULT 'pending',\n\t\"startedAt\" timestamp DEFAULT now(),\n\t\"completedAt\" timestamp,\n\t\"lastAccessedAt\" timestamp DEFAULT now(),\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\n);",
  "ALTER TABLE \"progress\" ADD CONSTRAINT \"progress_userId_users_id_fk\" FOREIGN KEY (\"userId\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
  "ALTER TABLE \"progress\" ADD CONSTRAINT \"progress_courseId_courses_id_fk\" FOREIGN KEY (\"courseId\") REFERENCES \"public\".\"courses\"(\"id\") ON DELETE no action ON UPDATE no action;",
  "ALTER TABLE \"progress\" ADD CONSTRAINT \"progress_enrollmentId_enrollments_id_fk\" FOREIGN KEY (\"enrollmentId\") REFERENCES \"public\".\"enrollments\"(\"id\") ON DELETE no action ON UPDATE no action;",
  "ALTER TYPE \"public\".\"role\" ADD VALUE 'professor' BEFORE 'admin';",
];
